[package]
name = "common"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
api = { path = "../../../../crates/api", optional = true }
thiserror = { version = "1.0.38", optional = true }

[features]
std = ["dep:thiserror"]
