[package]
name = "api"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
api-macro = { path = "../api-macro" }
sealed = { version = "0.4.0", optional = true }

[features]
# Compiles for host or wasm (choose exactly one).
host = ["dep:sealed"]
wasm = []
# Enables multivalue support (unstable).
multivalue = ["api-macro/multivalue"]
